// CART
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
export const EMPTY_CART = "EMPTY_CART";